packages:
  #- ./hayooFrontend
  - ./hayoo-server
  - ./hayooLib
  - ./hayooIndexer
  #- ./newHayooIndexer
  - ../hunt/hunt-api
  - ../hunt/hunt-client
  - ../hunt/hunt-crawler
  - ../hunt/hunt-searchengine
extra-deps:
  - bzlib-0.5.0.5
  - servant-0.12
  - servant-server-0.12
  - servant-client-0.12
  - servant-foreign-0.10.2
  - servant-client-core-0.12
  - store-0.3
  - store-core-0.3
  - data-r-tree-0.0.5.0
  - data-stringmap-1.0.1.1
  - hxt-xpath-9.1.2.2
  - hxt-cache-9.1.0.1
resolver: lts-9.13
