{-# LANGUAGE OverloadedStrings #-}
module Hayoo.Indexer.Hoogle.ParseTest
  ( suite
  ) where


import           Data.Monoid                ((<>))
import qualified Data.Text                  as T
import qualified Hayoo.Indexer.Hoogle.Parse as Hoogle
import           Test.Hspec                 (Spec, describe, it)
import           Test.Hspec.Megaparsec      (shouldFailOn, shouldParse,
                                             shouldSucceedOn)
import qualified Text.Megaparsec            as M



-- SUITE


suite :: Spec
suite =
  describe "preamble" $ do
    it "should parse preamble without comment" $ do
      M.parse Hoogle.preamble "" (testPreamble Nothing)
        `shouldParse` Hoogle.Package Nothing "servant" "0.12"

    it "should parse preamble with comment" $ do
      M.parse Hoogle.preamble "" (testPreamble (Just "-- | xx"))
        `shouldParse` Hoogle.Package (Just "xx") "servant" "0.12"



-- HELPERS


testPreamble :: Maybe T.Text -> T.Text
testPreamble comment =
  T.intercalate "\n"
  [ "-- Hoogle documentation, generated by Haddock"
  , "-- See Hoogle, http://www.haskell.org/hoogle/"
  , ""
  , case comment of
      Nothing ->
        ""

      Just c ->
        "\n" <> c
  , "@package servant"
  , "@version 0.12"
  ]
